# Generated by Django 2.2.7 on 2019-11-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20191121_0702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='name',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='email',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='message',
        ),
        migrations.AddField(
            model_name='budget',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2010-01-01'),
            preserve_default=False,
        ),
    ]
