# Generated by Django 2.2.7 on 2019-11-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20191121_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=999),
        ),
    ]
