# Generated by Django 2.2.7 on 2019-11-21 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20191121_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='owner',
        ),
    ]
