# Generated by Django 2.2.7 on 2019-11-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_remove_record_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='action',
            field=models.CharField(default='action', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=999),
        ),
    ]
