# Generated by Django 2.2.7 on 2019-11-21 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_auto_20191121_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
