//constants that hold a string
export const GET_LEADS = "GET_LEADS";
export const DELETE_LEADS = "DELETE_LEADS";
export const ADD_LEADS = "ADD_LEADS";
export const GET_LEAD = "GET_LEAD";
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
